repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: test_data
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: test_data
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: test_data

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.4
    hooks:
      - id: biome-format
        types: [json]
        args: ["--indent-style=space", "--indent-width=2"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml]
        args: [--tab-width=2]

  - repo: https://github.com/citation-file-format/cffconvert
    rev: 5295f87c0e261da61a7b919fc754e3a77edd98a7
    hooks:
      - id: validate-cff
