name: Fast-Forward PR

on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: >
        github.ref == 'refs/heads/develop' &&
        github.event.issue.pull_request != '' &&
        contains(github.event.comment.body, '/fast-forward') &&
        ${{ github.actor == 'hsaunders1904' || github.actor == 'je-cook' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get comment branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Checkout code into workspace directory
        if: ${{ steps.comment-branch.outputs.head_ref == 'develop_dependencies' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fast Forward PR
        id: ff-action
        if: ${{ steps.comment-branch.outputs.head_ref == 'develop_dependencies' }}
        uses: endre-spotlab/fast-forward-js-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
          staging_branch: "develop_dependencies"
          production_branch: "develop"
